In [60]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [61]:
data = pd.read_csv('/Users/rohanshenoy/Desktop/aero/data preprocessing/weatherAUS 2.csv')
data
#showing initial data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [62]:
#we drop the a few columns from the dataset and new dataset is X

label_encoder = LabelEncoder()
#we use label encoder to emcode the categorical column which have strings 
data['WindGustDir'] = label_encoder.fit_transform(data['WindGustDir'])
data['WindDir9am'] = label_encoder.fit_transform(data['WindDir9am'])
data['WindDir3pm'] = label_encoder.fit_transform(data['WindDir3pm'])
data['Location'] = label_encoder.fit_transform(data['Location'])
data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,2,13.4,22.9,0.6,NaN,NaN,13,44.0,13,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,2,7.4,25.1,0.0,NaN,NaN,14,44.0,6,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,2,12.9,25.7,0.0,NaN,NaN,15,46.0,13,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,2,9.2,28.0,0.0,NaN,NaN,4,24.0,9,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,2,17.5,32.3,1.0,NaN,NaN,13,41.0,1,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,41,2.8,23.4,0.0,NaN,NaN,0,31.0,9,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,2017-06-22,41,3.6,25.3,0.0,NaN,NaN,6,22.0,9,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,2017-06-23,41,5.4,26.9,0.0,NaN,NaN,3,37.0,9,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,2017-06-24,41,7.8,27.0,0.0,NaN,NaN,9,28.0,10,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,41,14.9,NaN,0.0,NaN,NaN,16,NaN,2,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [63]:
data = data.fillna(0) #replacing nan values with zero
data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,2,13.4,22.9,0.6,0.0,0.0,13,44.0,13,...,71.0,22.0,1007.7,1007.1,8.0,0.0,16.9,21.8,No,No
1,2008-12-02,2,7.4,25.1,0.0,0.0,0.0,14,44.0,6,...,44.0,25.0,1010.6,1007.8,0.0,0.0,17.2,24.3,No,No
2,2008-12-03,2,12.9,25.7,0.0,0.0,0.0,15,46.0,13,...,38.0,30.0,1007.6,1008.7,0.0,2.0,21.0,23.2,No,No
3,2008-12-04,2,9.2,28.0,0.0,0.0,0.0,4,24.0,9,...,45.0,16.0,1017.6,1012.8,0.0,0.0,18.1,26.5,No,No
4,2008-12-05,2,17.5,32.3,1.0,0.0,0.0,13,41.0,1,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,41,2.8,23.4,0.0,0.0,0.0,0,31.0,9,...,51.0,24.0,1024.6,1020.3,0.0,0.0,10.1,22.4,No,No
145456,2017-06-22,41,3.6,25.3,0.0,0.0,0.0,6,22.0,9,...,56.0,21.0,1023.5,1019.1,0.0,0.0,10.9,24.5,No,No
145457,2017-06-23,41,5.4,26.9,0.0,0.0,0.0,3,37.0,9,...,53.0,24.0,1021.0,1016.8,0.0,0.0,12.5,26.1,No,No
145458,2017-06-24,41,7.8,27.0,0.0,0.0,0.0,9,28.0,10,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,41,14.9,0.0,0.0,0.0,0.0,16,0.0,2,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,0

In [64]:
data.drop('Date',axis=1,inplace=True) #dropping date column as its useless/meaningless
data

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2,13.4,22.9,0.6,0.0,0.0,13,44.0,13,14,...,71.0,22.0,1007.7,1007.1,8.0,0.0,16.9,21.8,No,No
1,2,7.4,25.1,0.0,0.0,0.0,14,44.0,6,15,...,44.0,25.0,1010.6,1007.8,0.0,0.0,17.2,24.3,No,No
2,2,12.9,25.7,0.0,0.0,0.0,15,46.0,13,15,...,38.0,30.0,1007.6,1008.7,0.0,2.0,21.0,23.2,No,No
3,2,9.2,28.0,0.0,0.0,0.0,4,24.0,9,0,...,45.0,16.0,1017.6,1012.8,0.0,0.0,18.1,26.5,No,No
4,2,17.5,32.3,1.0,0.0,0.0,13,41.0,1,7,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,41,2.8,23.4,0.0,0.0,0.0,0,31.0,9,1,...,51.0,24.0,1024.6,1020.3,0.0,0.0,10.1,22.4,No,No
145456,41,3.6,25.3,0.0,0.0,0.0,6,22.0,9,3,...,56.0,21.0,1023.5,1019.1,0.0,0.0,10.9,24.5,No,No
145457,41,5.4,26.9,0.0,0.0,0.0,3,37.0,9,14,...,53.0,24.0,1021.0,1016.8,0.0,0.0,12.5,26.1,No,No
145458,41,7.8,27.0,0.0,0.0,0.0,9,28.0,10,3,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,41,14.9,0.0,0.0,0.0,0.0,16,0.0,2,2,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,0

In [65]:
data.replace(['No', 'Yes'], [0,1], inplace=True)
data
#binary encoding

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2,13.4,22.9,0.6,0.0,0.0,13,44.0,13,14,...,71.0,22.0,1007.7,1007.1,8.0,0.0,16.9,21.8,0,0
1,2,7.4,25.1,0.0,0.0,0.0,14,44.0,6,15,...,44.0,25.0,1010.6,1007.8,0.0,0.0,17.2,24.3,0,0
2,2,12.9,25.7,0.0,0.0,0.0,15,46.0,13,15,...,38.0,30.0,1007.6,1008.7,0.0,2.0,21.0,23.2,0,0
3,2,9.2,28.0,0.0,0.0,0.0,4,24.0,9,0,...,45.0,16.0,1017.6,1012.8,0.0,0.0,18.1,26.5,0,0
4,2,17.5,32.3,1.0,0.0,0.0,13,41.0,1,7,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,41,2.8,23.4,0.0,0.0,0.0,0,31.0,9,1,...,51.0,24.0,1024.6,1020.3,0.0,0.0,10.1,22.4,0,0
145456,41,3.6,25.3,0.0,0.0,0.0,6,22.0,9,3,...,56.0,21.0,1023.5,1019.1,0.0,0.0,10.9,24.5,0,0
145457,41,5.4,26.9,0.0,0.0,0.0,3,37.0,9,14,...,53.0,24.0,1021.0,1016.8,0.0,0.0,12.5,26.1,0,0
145458,41,7.8,27.0,0.0,0.0,0.0,9,28.0,10,3,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,0,0
145459,41,14.9,0.0,0.0,0.0,0.0,16,0.0,2,2,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,0,0

In [66]:
#can also use alternative approach of one hot encoding

#performing one hot encoding using get_dummies fn on the columns having str value
X=pd.read_csv('/Users/rohanshenoy/Desktop/aero/data preprocessing/weatherAUS 2.csv')
X = pd.get_dummies(data, columns=['Location','RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])
X

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,...,WindDir3pm_7,WindDir3pm_8,WindDir3pm_9,WindDir3pm_10,WindDir3pm_11,WindDir3pm_12,WindDir3pm_13,WindDir3pm_14,WindDir3pm_15,WindDir3pm_16
0,13.4,22.9,0.6,0.0,0.0,44.0,20.0,24.0,71.0,22.0,...,False,False,False,False,False,False,False,True,False,False
1,7.4,25.1,0.0,0.0,0.0,44.0,4.0,22.0,44.0,25.0,...,False,False,False,False,False,False,False,False,True,False
2,12.9,25.7,0.0,0.0,0.0,46.0,19.0,26.0,38.0,30.0,...,False,False,False,False,False,False,False,False,True,False
3,9.2,28.0,0.0,0.0,0.0,24.0,11.0,9.0,45.0,16.0,...,False,False,False,False,False,False,False,False,False,False
4,17.5,32.3,1.0,0.0,0.0,41.0,7.0,20.0,82.0,33.0,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2.8,23.4,0.0,0.0,0.0,31.0,13.0,11.0,51.0,24.0,...,False,False,False,False,False,False,False,False,False,False
145456,3.6,25.3,0.0,0.0,0.0,22.0,13.0,9.0,56.0,21.0,...,False,False,False,False,False,False,False,False,False,False
145457,5.4,26.9,0.0,0.0,0.0,37.0,9.0,9.0,53.0,24.0,...,False,False,False,False,False,False,False,True,False,False
145458,7.8,27.0,0.0,0.0,0.0,28.0,13.0,7.0,51.0,24.0,...,False,False,False,False,False,False,False,False,False,False
145459,14.9,0.0,0.0,0.0,0.0,0.0,17.0,17.0,62.0,36.0,...,False,False,False,False,False,False,False,False,False,False

In [67]:
data1=data #making a copy of the data so that i can show diff types of scaling

In [68]:
#now that our data is a little better we can do feature scaling

features = data.drop(columns='RainTomorrow', axis=1)
Y = data['RainTomorrow']

In [69]:
#performing min-max normalization
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
features_scaled = scaler.fit_transform(features)

# Convert the scaled features back to a DataFrame for easier handling
features_scaled_df = pd.DataFrame(features_scaled, columns=features.columns)

# Display the scaled features
print("\nScaled Features:")
print(features_scaled_df.head())

Scaled Features:
   Location   MinTemp   MaxTemp  Rainfall  Evaporation  Sunshine  WindGustDir  \
0  0.041667  0.516509  0.523629  0.001617          0.0       0.0       0.8125
1  0.041667  0.375000  0.565217  0.000000          0.0       0.0       0.8750
2  0.041667  0.504717  0.576560  0.000000          0.0       0.0       0.9375
3  0.041667  0.417453  0.620038  0.000000          0.0       0.0       0.2500
4  0.041667  0.613208  0.701323  0.002695          0.0       0.0       0.8125

   WindGustSpeed  WindDir9am  WindDir3pm  ...  WindSpeed3pm  Humidity9am  \
0       0.325926      0.8125      0.8750  ...      0.275862         0.71
1       0.325926      0.3750      0.9375  ...      0.252874         0.44
2       0.340741      0.8125      0.9375  ...      0.298851         0.38
3       0.177778      0.5625      0.0000  ...      0.103448         0.45
4       0.303704      0.0625      0.4375  ...      0.229885         0.82

   Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm   Temp9am  \
0         0.22     0.968012     0.968738  0.888889  0.000000  0.508439
1         0.25     0.970797     0.969411  0.000000  0.000000  0.514768
2         0.30     0.967915     0.970277  0.000000  0.222222  0.594937
3         0.16     0.977522     0.974221  0.000000  0.000000  0.533755
4         0.33     0.970989     0.967680  0.777778  0.888889  0.527426

    Temp3pm  RainToday
0  0.522073        0.0
1  0.570058        0.0
2  0.548944        0.0
3  0.612284        0.0
4  0.673704        0.0

[5 rows x 21 columns]

In [70]:
#performing standardization

features1 = data1.drop(columns='RainTomorrow', axis=1)
Y = data1['RainTomorrow']

from sklearn.preprocessing import StandardScaler

# Perform feature scaling using standardization
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features1)

# Convert the scaled features back to a DataFrame for easier handling
features_scaled_df = pd.DataFrame(features_scaled, columns=features1.columns)

# Display the scaled features
print("\nScaled Features:")
print(features_scaled_df.head())

Scaled Features:
   Location   MinTemp   MaxTemp  Rainfall  Evaporation  Sunshine  WindGustDir  \
0 -1.531666  0.205232 -0.016205 -0.203581    -0.746516 -0.845389     0.944029
1 -1.531666 -0.720312  0.280780 -0.275097    -0.746516 -0.845389     1.145167
2 -1.531666  0.128104  0.361776 -0.275097    -0.746516 -0.845389     1.346306
3 -1.531666 -0.442649  0.672260 -0.275097    -0.746516 -0.845389    -0.866215
4 -1.531666  0.837688  1.252731 -0.155903    -0.746516 -0.845389     0.944029

   WindGustSpeed  WindDir9am  WindDir3pm  ...  WindSpeed3pm  Humidity9am  \
0       0.407796    1.027318    1.265374  ...      0.628382     0.160852
1       0.407796   -0.394948    1.476352  ...      0.409059    -1.125609
2       0.527921    1.027318    1.476352  ...      0.847705    -1.411490
3      -0.793463    0.214594   -1.688306  ...     -1.016540    -1.077963
4       0.227607   -1.410853   -0.211466  ...      0.189736     0.684967

   Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm   Temp9am  \
0    -1.251090     0.307741     0.312970  1.679577 -0.875693  0.017246
1    -1.116768     0.317092     0.315235 -0.874270 -0.875693  0.061940
2    -0.892897     0.307419     0.318147 -0.874270 -0.219635  0.628056
3    -1.519736     0.339661     0.331412 -0.874270 -0.875693  0.196020
4    -0.758574     0.317736     0.309411  1.360346  1.748540  0.151327

    Temp3pm  RainToday
0  0.085732  -0.529795
1  0.413155  -0.529795
2  0.269089  -0.529795
3  0.701288  -0.529795
4  1.120390  -0.529795

[5 rows x 21 columns]

In [71]:
#dividing data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=10)

In [72]:
x_train

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
96775,0,8.5,23.1,0.0,0.6,9.0,6,43.0,5,6,...,26.0,45.0,23.0,1012.3,1007.8,0.0,0.0,17.5,22.6,0
96840,0,17.9,22.1,0.0,10.2,11.5,11,46.0,11,12,...,24.0,64.0,40.0,1017.9,1019.8,0.0,0.0,18.6,21.6,0
66795,19,11.1,17.5,0.4,4.2,1.0,14,52.0,7,15,...,28.0,55.0,47.0,1017.2,1017.6,7.0,7.0,14.7,16.6,0
104598,28,3.6,22.1,0.0,7.2,11.3,8,41.0,9,12,...,19.0,54.0,32.0,1022.8,1019.6,4.0,4.0,13.3,21.3,0
137064,3,7.3,23.6,0.0,11.8,10.5,10,41.0,9,9,...,20.0,16.0,14.0,1021.4,1017.6,0.0,8.0,18.6,23.3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9372,11,14.4,24.8,0.0,6.2,12.6,16,0.0,7,4,...,22.0,61.0,56.0,1022.7,1020.4,1.0,1.0,21.9,24.2,0
105595,48,26.7,43.7,0.0,16.0,12.4,9,44.0,9,12,...,7.0,37.0,12.0,1008.2,1005.0,1.0,1.0,30.1,41.4,0
93553,39,17.7,28.6,0.0,6.6,8.3,1,31.0,11,4,...,20.0,71.0,57.0,1016.9,1014.1,7.0,1.0,24.5,27.1,0
94735,39,25.6,34.2,11.4,4.0,5.5,15,46.0,13,13,...,15.0,65.0,47.0,998.3,995.4,7.0,7.0,28.7,33.5,1
83209,12,1.4,16.0,0.2,2.0,8.3,9,39.0,16,8,...,19.0,0.0,0.0,1038.8,1036.6,0.0,0.0,7.5,14.5,0

In [73]:
x_test

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
124601,36,16.5,27.1,0.8,0.0,0.0,1,26.0,0,1,...,7.0,79.0,48.0,0.0,0.0,0.0,0.0,19.6,25.7,0
19713,26,10.8,15.7,0.0,0.0,0.0,11,48.0,12,8,...,37.0,41.0,47.0,1018.7,1019.7,0.0,0.0,13.2,15.3,0
98025,0,14.2,23.3,0.0,1.8,5.3,4,35.0,4,3,...,15.0,57.0,44.0,1018.7,1015.8,0.0,0.0,18.4,22.9,0
58336,6,1.7,9.9,0.0,0.8,0.0,4,37.0,1,4,...,20.0,88.0,81.0,1013.8,1009.5,7.0,8.0,5.5,8.5,0
116285,29,8.1,21.4,11.2,0.0,11.9,0,41.0,0,10,...,9.0,48.0,33.0,1024.4,1021.2,0.0,0.0,14.5,20.6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65552,19,4.4,22.8,0.0,4.6,9.9,3,59.0,3,3,...,33.0,42.0,26.0,1024.3,1021.3,7.0,7.0,14.4,20.5,0
59794,6,4.6,17.5,3.0,1.1,0.0,8,31.0,5,15,...,20.0,89.0,49.0,1026.0,1024.1,0.0,0.0,11.5,17.2,1
4308,4,6.4,17.6,0.0,0.0,0.0,10,37.0,12,11,...,13.0,76.0,91.0,1030.3,1028.3,0.0,0.0,11.9,12.5,0
101795,22,7.4,14.9,0.6,0.6,4.7,13,52.0,6,14,...,20.0,96.0,72.0,1019.0,1016.0,8.0,7.0,10.0,13.7,0
96871,0,15.2,25.2,0.0,0.0,10.5,15,43.0,10,12,...,24.0,50.0,40.0,1022.6,1019.0,0.0,0.0,17.3,22.3,0

In [74]:
y_train

96775     0
96840     0
66795     0
104598    0
137064    0
         ..
9372      0
105595    0
93553     0
94735     0
83209     0
Name: RainTomorrow, Length: 116368, dtype: int64

In [75]:
y_test

124601    0
19713     0
98025     1
58336     0
116285    0
         ..
65552     0
59794     0
4308      1
101795    1
96871     0
Name: RainTomorrow, Length: 29092, dtype: int64